org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

## Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.234
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod
mod_id=villagershop
mod_name=VillagerShop
mod_license=LGPL-3.0-only
mod_version=1.5.0
mod_group_id=com.villagershop
mod_authors=GusFrip
mod_description=Crée des boutiques multijoueur gérées par des villageois. Pose un Comptoir de marchand, configure tes ventes et achats, et laisse un villageois servir tes clients.

## Dependencies
patchouli_version=1.21.1-93-NEOFORGE
