org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

## Environment
minecraft_version=1.21.1
loader_version=0.19.2
fabric_version=0.116.12+1.21.1

## Mod
mod_id=villagershop
mod_name=VillagerShop
mod_license=LGPL-3.0-only
mod_version=1.5.0
mod_group_id=com.villagershop
mod_authors=GusFrip

## Dependencies
patchouli_version=1.21.1-93-FABRIC
